name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use your preferred version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Start FastAPI Server
      - name: Start FastAPI Server
        run: |
          uvicorn apiserver:app --host 127.0.0.1 --port 8000 &
          sleep 5  # Wait for the server to be up and running

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          pytest testAutomation.py
